# Generated by Django 5.2 on 2025-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
