# Generated by Django 5.2 on 2025-06-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
