# Generated by Django 5.2 on 2025-06-08 09:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_publicacion_imagen_destacada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='archivo_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
