# Generated by Django 5.2 on 2025-05-12 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tipo', models.CharField(choices=[('articulo', 'Articulo'), ('imagen', 'Imagen'), ('video', 'Video')], default='articulo', max_length=10)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('url_video', models.URLField(blank=True, null=True)),
                ('etiqueta', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo_video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm'])])),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
    ]
