# Generated by Django 5.2 on 2025-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_publicacion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='archivo_video',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='video_cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
