# Generated by Django 5.2 on 2025-06-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_publicacion_archivo_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='video_cloudinary_url',
        ),
    ]
