# Generated by Django 5.2 on 2025-06-12 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_obra_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='obra',
            name='creado_en',
            field=models.PositiveIntegerField(default=2025, help_text='Utiliza este formato: AAAA', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
